services:
  nukiblinker:
    build: .
    container_name: nukiblinker
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./homekit:/app/.homekit
