services:
  nukiblinker:
    image: ghcr.io/nicdobler/nukiblinker:latest
    container_name: nukiblinker
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./secrets.yaml:/app/secrets.yaml
      - ./homekit:/app/.homekit
      - ./logs:/app/logs
