#!/usr/bin/env bash
# Launch REAL parallel Cascade sessions (one per GitHub issue) in isolated git
# worktrees, then wait for their PRs to go green so the orchestrator can wrap up.
#
# A single Cascade conversation runs issues sequentially; true wall-clock
# parallelism needs one Windsurf window per worktree. This launcher creates a
# worktree + branch + task brief per issue, opens a Windsurf/VS Code window on
# each, and (with --wait) polls GitHub until every PR is green.
#
# In each new window, type one command:  /orchestrate-run
# (Cascade has no public API to auto-inject a prompt, so this paste is required.)
#
# Usage:
#   ./script/orchestrate-parallel.sh 140 141 142            # launch only
#   ./script/orchestrate-parallel.sh --wait 140 141 142     # launch + poll CI
#   ./script/orchestrate-parallel.sh --merge 140 141        # launch + poll + merge
#   REPO=owner/repo POLL=30 ./script/orchestrate-parallel.sh --wait 140

set -euo pipefail

REPO="${REPO:-nicdobler/NukiBlinker}"
POLL="${POLL:-30}"
WAIT=false
MERGE=false
NO_LAUNCH="${NO_LAUNCH:-false}"
ISSUES=()

for arg in "$@"; do
  case "$arg" in
    --wait) WAIT=true ;;
    --merge) MERGE=true; WAIT=true ;;
    --no-launch) NO_LAUNCH=true ;;
    *[!0-9]*) echo "Ignoring non-numeric arg: $arg" ;;
    *) ISSUES+=("$arg") ;;
  esac
done

if [ "${#ISSUES[@]}" -eq 0 ]; then
  echo "No issue numbers given. Example: ./script/orchestrate-parallel.sh --wait 140 141"
  exit 1
fi

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
WORKTREE_ROOT="$(dirname "$REPO_ROOT")/NukiBlinker-wt"

slug() { echo "$1" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9]+/-/g; s/^-+//; s/-+$//' | cut -c1-40 | sed -E 's/-+$//'; }

editor_cmd() {
  for c in windsurf code; do
    if command -v "$c" >/dev/null 2>&1; then echo "$c"; return; fi
  done
  echo ""
}

issue_type() { # echoes "fix" or "feat"
  local n="$1" title="$2" labels="$3"
  if echo "$labels" | grep -qiw bug || echo "$title" | grep -qiE '\b(bug|fix|fixes|error|crash|broken|incorrect)\b'; then
    echo fix
  else
    echo feat
  fi
}

write_brief() { # $1 path, $2 number, $3 branch, $4 type, $5 title
  local wf; wf=$([ "$4" = fix ] && echo /fix-bug || echo /new-feature)
  cat > "$1" <<EOF
# Orchestrated task — issue #$2

> Auto-generated by \`script/orchestrate-parallel.sh\`. Do NOT commit this file.

- **Repo**: $REPO
- **Branch**: \`$3\` (already checked out in this worktree)
- **Type**: $4
- **Title**: $5

You are an autonomous agent in an isolated git worktree. Execute end to end:

1. Read the issue: \`gh issue view $2 --repo $REPO\`
2. Load context: README.md, Agents.md, specs/, and the relevant source + tests.
3. Follow the **$wf** workflow on THIS branch: implement, tests, docs/specs/CHANGELOG.
4. Commit, then \`git push -u origin $3\`
5. \`gh pr create --repo $REPO --base main --head $3 --title "..." --body "Closes #$2. ..."\`
6. Drive CI green autonomously (poll \`gh pr checks\`, fix, re-push). Stop after 2
   failed attempts on the same failure and re-plan.

Hard rules: do NOT merge, do NOT touch main, do NOT commit .orchestrate-task.md.
EOF
}

declare -a BRANCHES TYPES NUMBERS
ED="$([ "$NO_LAUNCH" = true ] && echo "" || editor_cmd)"

echo ""
echo "=== Parallel orchestration: ${ISSUES[*]} ==="
for n in "${ISSUES[@]}"; do
  json="$(gh issue view "$n" --repo "$REPO" --json number,title,labels)"
  title="$(echo "$json" | python3 -c 'import sys,json;print(json.load(sys.stdin)["title"])')"
  labels="$(echo "$json" | python3 -c 'import sys,json;print(",".join(l["name"] for l in json.load(sys.stdin)["labels"]))')"
  type="$(issue_type "$n" "$title" "$labels")"
  branch="$type/$n-$(slug "$title")"
  NUMBERS+=("$n"); BRANCHES+=("$branch"); TYPES+=("$type")

  echo ""
  echo "[$type] #$n -> $branch"
  "$REPO_ROOT/script/worktree.sh" new "$branch"

  wt="$WORKTREE_ROOT/$(echo "$branch" | tr '/\\' '-')"
  write_brief "$wt/.orchestrate-task.md" "$n" "$branch" "$type" "$title"

  if [ -n "$ED" ]; then
    "$ED" -n "$wt" >/dev/null 2>&1 &
    echo "  [launch] opened in $ED. In THAT window, type:  /orchestrate-run"
  else
    echo "  [manual] open this folder in Windsurf, then type /orchestrate-run:"
    echo "           $wt"
  fi
done

echo ""
echo "Prompt to paste in every new window:  /orchestrate-run"

[ "$WAIT" = true ] || { echo "Not waiting (add --wait to poll, --merge to auto-merge)."; exit 0; }

# Returns NO_PR | PENDING | SUCCESS | FAILURE on stdout; PR number on fd 3-less via global.
pr_rollup() {
  local branch="$1"
  local num
  num="$(gh pr list --repo "$REPO" --head "$branch" --state open --json number --jq '.[0].number' 2>/dev/null || true)"
  if [ -z "$num" ] || [ "$num" = "null" ]; then echo "NO_PR"; return; fi
  PR_NUMBER="$num"
  local rollup
  rollup="$(gh pr view "$num" --repo "$REPO" --json statusCheckRollup --jq '
    [.statusCheckRollup[] | (.state // .conclusion // .status)] as $s
    | if ($s | length) == 0 then "PENDING"
      elif any($s[]; . == "FAILURE" or . == "ERROR" or . == "CANCELLED" or . == "TIMED_OUT" or . == "ACTION_REQUIRED") then "FAILURE"
      elif any($s[]; . == "PENDING" or . == "EXPECTED" or . == "QUEUED" or . == "IN_PROGRESS" or . == null) then "PENDING"
      else "SUCCESS" end' 2>/dev/null || echo PENDING)"
  echo "$rollup"
}

echo ""
echo "Waiting for PRs to go green (poll ${POLL}s)... Ctrl+C to stop."
while true; do
  all_green=true
  out=""
  for i in "${!BRANCHES[@]}"; do
    PR_NUMBER=""
    state="$(pr_rollup "${BRANCHES[$i]}")"
    case "$state" in
      SUCCESS) out+="  [green]   #${NUMBERS[$i]} ${BRANCHES[$i]} (PR #${PR_NUMBER})\n" ;;
      FAILURE) all_green=false; out+="  [FAILED]  #${NUMBERS[$i]} ${BRANCHES[$i]} (PR #${PR_NUMBER}) — agent must fix\n" ;;
      PENDING) all_green=false; out+="  [running] #${NUMBERS[$i]} ${BRANCHES[$i]} (PR #${PR_NUMBER})\n" ;;
      NO_PR)   all_green=false; out+="  [no PR]   #${NUMBERS[$i]} ${BRANCHES[$i]} — agent not finished\n" ;;
    esac
  done
  clear
  echo "=== Parallel orchestration status @ $(date +%H:%M:%S) ==="
  printf "%b" "$out"
  $all_green && break
  sleep "$POLL"
done

echo ""
echo "All PRs are green."

[ "$MERGE" = true ] || { echo "Run with --merge to squash-merge in order."; exit 0; }

echo ""
echo "Merging in issue order..."
for i in "${!BRANCHES[@]}"; do
  PR_NUMBER=""
  [ "$(pr_rollup "${BRANCHES[$i]}")" = SUCCESS ] || { echo "  Skipping #${NUMBERS[$i]} (not green)."; continue; }
  echo "  Merging PR #${PR_NUMBER} (#${NUMBERS[$i]} ${BRANCHES[$i]})..."
  if ! gh pr merge "$PR_NUMBER" --repo "$REPO" --squash --delete-branch; then
    echo "  Merge failed (conflict?). Rebase ${BRANCHES[$i]} on main and retry."
    break
  fi
  # Rebase remaining worktrees so conflicts surface early.
  for j in "${!BRANCHES[@]}"; do
    [ "$j" -le "$i" ] && continue
    wt="$WORKTREE_ROOT/$(echo "${BRANCHES[$j]}" | tr '/\\' '-')"
    git -C "$wt" fetch origin >/dev/null 2>&1 || true
    if git -C "$wt" rebase origin/main >/dev/null 2>&1; then
      git -C "$wt" push --force-with-lease origin "${BRANCHES[$j]}" >/dev/null 2>&1 || true
    else
      echo "  Rebase conflict in ${BRANCHES[$j]} — resolve manually, then re-run with --merge."
      git -C "$wt" rebase --abort >/dev/null 2>&1 || true
    fi
  done
done

echo ""
echo "Done. Clean up worktrees with: ./script/worktree.sh remove <branch>"
