<#
.SYNOPSIS
    Launch REAL parallel Cascade sessions (one per GitHub issue) in isolated git
    worktrees, then wait for their PRs to go green so the orchestrator can wrap up.

.DESCRIPTION
    A single Cascade conversation runs issues sequentially. True wall-clock
    parallelism needs one Windsurf window per worktree. This launcher does the
    plumbing:

      1. For each issue: classify it (feat/fix), create a worktree + branch from
         origin/main, and drop a per-worktree task brief (.orchestrate-task.md).
      2. Open a NEW Windsurf (or VS Code) window on each worktree folder.
      3. In each new window, the human types one command:  /orchestrate-run
         The agent there reads .orchestrate-task.md and executes it end to end
         (implement -> test -> push -> open PR -> drive CI green). Cascade has no
         public API to auto-inject a prompt, so this one paste is unavoidable.
      4. With -Wait, this script polls GitHub until every issue has an open PR
         with all checks passed (or a failure/no-PR is surfaced).
      5. With -Merge, once all are green it squash-merges in issue order, rebasing
         the remaining worktrees after each merge (stops on conflict for a manual
         rebase, per Rule 7).

    Agents only edit + push inside their worktree; CI is the sole validation gate.

.PARAMETER Issues
    Issue numbers to process in order, e.g. -Issues 140,141,142

.PARAMETER Repo
    owner/repo slug. Default: nicdobler/NukiBlinker

.PARAMETER Wait
    Poll GitHub until every PR is green (or failed). Implied by -Merge.

.PARAMETER Merge
    After all PRs are green, squash-merge them in issue order and clean up.

.PARAMETER PollSeconds
    Poll interval while waiting. Default: 30.

.PARAMETER NoLaunch
    Create worktrees + briefs but do NOT open editor windows (print instructions
    instead). Useful on headless machines or to launch windows manually.

.EXAMPLE
    .\script\orchestrate-parallel.ps1 -Issues 140,141,142 -Wait

.EXAMPLE
    .\script\orchestrate-parallel.ps1 -Issues 140,141 -Merge
#>

param(
    [Parameter(Mandatory)][int[]]$Issues,
    [string]$Repo = 'nicdobler/NukiBlinker',
    [switch]$Wait,
    [switch]$Merge,
    [int]$PollSeconds = 30,
    [switch]$NoLaunch
)

$ErrorActionPreference = 'Stop'
$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$WorktreeRoot = Join-Path (Split-Path $RepoRoot -Parent) 'NukiBlinker-wt'

function Get-Slug([string]$text) {
    $s = ($text -replace '[^a-zA-Z0-9]+', '-').Trim('-').ToLower()
    if ($s.Length -gt 40) { $s = $s.Substring(0, 40).Trim('-') }
    return $s
}

function Get-IssueInfo([int]$issue) {
    $json = gh issue view $issue --repo $Repo --json number,title,labels | ConvertFrom-Json
    $labels = @($json.labels | ForEach-Object { $_.name.ToLower() })
    $isBug = ($labels -contains 'bug') -or ($json.title -match '(?i)\b(bug|fix|fixes|error|crash|broken|incorrect)\b')
    $type = if ($isBug) { 'fix' } else { 'feat' }
    return [pscustomobject]@{
        Number = $issue
        Title  = $json.title
        Type   = $type
        Branch = "$type/$issue-$(Get-Slug $json.title)"
    }
}

function Get-EditorCommand {
    foreach ($candidate in 'windsurf', 'code') {
        if (Get-Command $candidate -ErrorAction SilentlyContinue) { return $candidate }
    }
    return $null
}

function Write-TaskBrief($info, [string]$path) {
    $workflow = if ($info.Type -eq 'fix') { '/fix-bug' } else { '/new-feature' }
    $content = @"
# Orchestrated task — issue #$($info.Number)

> Auto-generated by ``script/orchestrate-parallel.ps1``. Do NOT commit this file.

- **Repo**: $Repo
- **Branch**: ``$($info.Branch)`` (already checked out in this worktree)
- **Type**: $($info.Type)
- **Title**: $($info.Title)

You are an autonomous agent in an isolated git worktree. Execute this task end to end:

1. Read the issue: ``gh issue view $($info.Number) --repo $Repo``
2. Load context: ``README.md``, ``Agents.md``, ``specs/``, and the relevant source + tests.
3. Follow the **$workflow** workflow on THIS branch: implement, write/adjust tests,
   update docs/specs/CHANGELOG.
4. Commit, then push: ``git push -u origin $($info.Branch)``
5. Open a PR: ``gh pr create --repo $Repo --base main --head $($info.Branch) --title "..." --body "Closes #$($info.Number). ..."``
6. Drive CI to green autonomously (poll ``gh pr checks``, diagnose failures, fix, re-push).
   Reset rule: STOP after 2 failed attempts on the same failure and re-plan.

Hard rules:
- Do **NOT** merge, and do **NOT** touch ``main`` — the orchestrator merges in order.
- Do **NOT** commit ``.orchestrate-task.md``.
- Keep changes scoped to this issue's files to minimise cross-branch merge conflicts.
"@
    Set-Content -Path $path -Value $content -Encoding UTF8
}

function Get-PrRollup($info) {
    # Returns: NO_PR | PENDING | SUCCESS | FAILURE, plus the PR number when known.
    $prs = gh pr list --repo $Repo --head $info.Branch --state open --json number 2>$null | ConvertFrom-Json
    if (-not $prs -or $prs.Count -eq 0) {
        return [pscustomobject]@{ State = 'NO_PR'; Number = $null }
    }
    $number = $prs[0].number
    $view = gh pr view $number --repo $Repo --json statusCheckRollup | ConvertFrom-Json
    $checks = @($view.statusCheckRollup)
    if ($checks.Count -eq 0) {
        return [pscustomobject]@{ State = 'PENDING'; Number = $number }
    }
    $pending = $false; $failed = $false
    foreach ($c in $checks) {
        # CheckRun uses status/conclusion; StatusContext uses state.
        $status = $c.status; $conclusion = $c.conclusion; $state = $c.state
        if ($state) {
            if ($state -in @('PENDING', 'EXPECTED')) { $pending = $true }
            elseif ($state -in @('FAILURE', 'ERROR')) { $failed = $true }
        } else {
            if ($status -ne 'COMPLETED') { $pending = $true }
            elseif ($conclusion -in @('FAILURE', 'CANCELLED', 'TIMED_OUT', 'STARTUP_FAILURE', 'ACTION_REQUIRED')) { $failed = $true }
        }
    }
    $resultState = if ($failed) { 'FAILURE' } elseif ($pending) { 'PENDING' } else { 'SUCCESS' }
    return [pscustomobject]@{ State = $resultState; Number = $number }
}

# --- 1. Create worktrees + briefs + launch windows ------------------------

Write-Host ""
Write-Host "=== Parallel orchestration: $($Issues -join ', ') ===" -ForegroundColor Cyan
$editor = if ($NoLaunch) { $null } else { Get-EditorCommand }
$infos = @()

foreach ($issue in $Issues) {
    $info = Get-IssueInfo $issue
    $infos += $info
    Write-Host ""
    Write-Host "[$($info.Type)] #$($info.Number) -> $($info.Branch)" -ForegroundColor Yellow

    & (Join-Path $PSScriptRoot 'worktree.ps1') -Action new -Branch $info.Branch | Out-Host

    $slug = ($info.Branch -replace '[/\\]', '-')
    $wtPath = Join-Path $WorktreeRoot $slug
    Write-TaskBrief $info (Join-Path $wtPath '.orchestrate-task.md')

    if ($editor) {
        Start-Process $editor -ArgumentList @('-n', $wtPath)
        Write-Host "  [launch] opened in $editor. In THAT window, type:  /orchestrate-run" -ForegroundColor Green
    } else {
        Write-Host "  [manual] open this folder in Windsurf, then type:  /orchestrate-run" -ForegroundColor Green
        Write-Host "           $wtPath" -ForegroundColor DarkGray
    }
}

Write-Host ""
Write-Host "Each spawned agent reads '.orchestrate-task.md' and runs autonomously." -ForegroundColor Gray
Write-Host "Prompt to paste in every new window:  /orchestrate-run" -ForegroundColor Gray

# --- 2. Wait for all PRs to go green --------------------------------------

if (-not ($Wait -or $Merge)) {
    Write-Host ""
    Write-Host "Not waiting (omit nothing / add -Wait to poll, -Merge to auto-merge)." -ForegroundColor DarkGray
    return
}

Write-Host ""
Write-Host "Waiting for PRs to go green (poll ${PollSeconds}s)... Ctrl+C to stop." -ForegroundColor Cyan
do {
    Start-Sleep -Seconds 1
    $allGreen = $true
    $anyFailed = $false
    $lines = @()
    foreach ($info in $infos) {
        $r = Get-PrRollup $info
        switch ($r.State) {
            'SUCCESS' { $lines += "  [green]   #$($info.Number) $($info.Branch) (PR #$($r.Number))" }
            'FAILURE' { $allGreen = $false; $anyFailed = $true; $lines += "  [FAILED]  #$($info.Number) $($info.Branch) (PR #$($r.Number)) — agent must fix" }
            'PENDING' { $allGreen = $false; $lines += "  [running] #$($info.Number) $($info.Branch) (PR #$($r.Number))" }
            'NO_PR'   { $allGreen = $false; $lines += "  [no PR]   #$($info.Number) $($info.Branch) — agent not finished" }
        }
    }
    Clear-Host
    Write-Host "=== Parallel orchestration status @ $(Get-Date -Format HH:mm:ss) ===" -ForegroundColor Cyan
    $lines | ForEach-Object { Write-Host $_ }
    if (-not $allGreen) { Start-Sleep -Seconds $PollSeconds }
} while (-not $allGreen)

Write-Host ""
Write-Host "All PRs are green." -ForegroundColor Green

# --- 3. Optional: merge in issue order, rebasing the rest -----------------

if (-not $Merge) {
    Write-Host "Run with -Merge to squash-merge in order, or merge manually." -ForegroundColor DarkGray
    return
}

Write-Host ""
Write-Host "Merging in issue order..." -ForegroundColor Cyan
$remaining = [System.Collections.ArrayList]@($infos)
foreach ($info in $infos) {
    $r = Get-PrRollup $info
    if ($r.State -ne 'SUCCESS') {
        Write-Host "  Skipping #$($info.Number): not green anymore ($($r.State))." -ForegroundColor Yellow
        continue
    }
    Write-Host "  Merging PR #$($r.Number) (#$($info.Number) $($info.Branch))..."
    gh pr merge $r.Number --repo $Repo --squash --delete-branch
    if ($LASTEXITCODE -ne 0) {
        Write-Host "  Merge failed (likely a conflict). Rebase this branch on main and retry:" -ForegroundColor Red
        Write-Host "    git -C `"$WorktreeRoot\$(($info.Branch -replace '[/\\]','-'))`" fetch origin; git ... rebase origin/main" -ForegroundColor DarkGray
        break
    }
    $remaining.Remove($info) | Out-Null
    # Rebase the remaining worktrees so conflicts surface early.
    foreach ($other in $remaining) {
        $otherPath = Join-Path $WorktreeRoot ($other.Branch -replace '[/\\]', '-')
        git -C $otherPath fetch origin 2>$null
        git -C $otherPath rebase origin/main 2>$null
        if ($LASTEXITCODE -ne 0) {
            Write-Host "  Rebase conflict in $($other.Branch) — resolve manually, then re-run with -Merge." -ForegroundColor Yellow
            git -C $otherPath rebase --abort 2>$null
        } else {
            git -C $otherPath push --force-with-lease origin $other.Branch 2>$null
        }
    }
}

Write-Host ""
Write-Host "Done. Remember to clean up worktrees:  .\script\worktree.ps1 -Action remove -Branch <branch>" -ForegroundColor Gray
