#!/usr/bin/env bash
# Run tests + lint on Mac, create a GitHub issue if anything fails.
# Requirements: gh CLI authenticated, poetry installed.
# Usage: ./script/test-and-report.sh

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

BRANCH="$(git branch --show-current)"
COMMIT="$(git rev-parse --short HEAD)"
TIMESTAMP="$(date -u '+%Y-%m-%d %H:%M UTC')"

LINT_OK=true
TEST_OK=true
LINT_OUTPUT=""
TEST_OUTPUT=""

echo "=== Running lint ==="
if LINT_OUTPUT="$(make lint 2>&1)"; then
  echo "  ✅ Lint passed"
else
  LINT_OK=false
  echo "  ❌ Lint failed"
fi

echo "=== Running tests ==="
if TEST_OUTPUT="$(make test 2>&1)"; then
  echo "  ✅ Tests passed"
else
  TEST_OK=false
  echo "  ❌ Tests failed"
fi

if $LINT_OK && $TEST_OK; then
  echo ""
  echo "✅ All checks passed — no issue created."
  exit 0
fi

# Build issue body
TITLE="Test failures on \`$BRANCH\` @ $COMMIT"

BODY="## Automated Test Report

**Branch**: \`$BRANCH\`
**Commit**: \`$COMMIT\`
**Date**: $TIMESTAMP
**Machine**: $(uname -s) $(uname -m)
"

if ! $LINT_OK; then
  BODY+="
### ❌ Lint (flake8)

\`\`\`
$LINT_OUTPUT
\`\`\`
"
fi

if ! $TEST_OK; then
  BODY+="
### ❌ Tests (pytest)

\`\`\`
$TEST_OUTPUT
\`\`\`
"
fi

BODY+="
---
*Auto-generated by \`script/test-and-report.sh\`*"

echo ""
echo "=== Creating GitHub issue ==="
ISSUE_URL="$(gh issue create \
  --title "$TITLE" \
  --body "$BODY" \
  --label "bug" \
  2>&1)"

echo "📋 Issue created: $ISSUE_URL"
